spring:
  application:
    name: eureka-discovery-service
server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    renewal-percent-threshold: 0.49