version: '1'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  dbperson:
    image: "postgres:15.2"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: person
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      restart: unless-stopped

  dbworkout:
    image: "postgres:15.2"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: workout
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      restart: unless-stopped

  user:
    build: ./userService
    image: user-service
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - dbperson
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbperson:5432/person
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root


  workout:
    build: ./workoutService
    image: workout-service
    container_name: workout-service
    ports:
      - "8081:8081"
    depends_on:
      - dbworkout
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbworkout:5432/workout
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

